### ISSUE TITLE
Dockerize build

### ISSUE THREAD

**Issue by xor-gate** [miloyip/nativejson-benchmark#25] opened 2016-01-21 09:25 UTC
As the test are a little pain to build we can Dockerize the build process so it can be used for everyone in a consistent way. Without sacrificing slowness of benchmarks when running on continues integration platforms, e.g Travis CI.  (See discussion from other issue: https://github.com/miloyip/nativejson-benchmark/issues/9#issuecomment-173423516)

I have a initial file here: https://github.com/xor-gate/nativejson-benchmark/blob/dockerize/Dockerfile
On my branch: https://github.com/xor-gate/nativejson-benchmark/tree/dockerize

**Comment by xor-gate** [comment] 2016-01-21 09:38
@miloyip In the README.md you notice we need `premake5` but the `build/premake.sh` calls `premake4`. This is a inconsistency.

**Comment by miloyip** [comment] 2016-01-22 04:09
The premake inconsistency and several build problems have been fixed in 0eed631b8ba4158dddcb58c8537e97bad2068bd6

**Comment by xor-gate** [comment] 2016-01-22 21:36
I finaly get some output. It seems the regex is broken, i'm running under debian (8) jessie amd64:

```
+ /bin/sh -c ./premake.sh
Building configurations...
Running action 'gmake'...
Generated gmake/benchmark.make...
Generated gmake/jsonclibs.make...
Generated gmake/nativejson.make...
Generated gmake/jsonstat.make...
Generated gmake/jsonclibs2.make...
Generated gmake/jsonstat_arduinojsontest.make...
Generated gmake/jsonstat_cajuntest.make...
Generated gmake/jsonstat_casablancatest.make...
Generated gmake/jsonstat_cjsontest.make...
Generated gmake/jsonstat_configurutest.make...
Generated gmake/jsonstat_dropboxjson11test.make...
Generated gmake/jsonstat_fastjsontest.make...
Generated gmake/jsonstat_gasontest.make...
Generated gmake/jsonstat_janssontest.make...
Generated gmake/jsonstat_jeayesontest.make...
Generated gmake/jsonstat_jsonboxtest.make...
Generated gmake/jsonstat_jsonconstest.make...
Generated gmake/jsonstat_jsoncpptest.make...
Generated gmake/jsonstat_jsonctest.make...
Generated gmake/jsonstat_jsonspirittest.make...
Generated gmake/jsonstat_jsonxxtest.make...
Generated gmake/jsonstat_jvartest.make...
Generated gmake/jsonstat_jzontest.make...
Generated gmake/jsonstat_nbsdxsimplejsontest.make...
Generated gmake/jsonstat_nlohmanntest.make...
Generated gmake/jsonstat_parsontest.make...
Generated gmake/jsonstat_picojsontest.make...
Generated gmake/jsonstat_rapidjsonautoutftest.make...
Generated gmake/jsonstat_rapidjsonfullprectest.make...
Generated gmake/jsonstat_rapidjsoninsitutest.make...
Generated gmake/jsonstat_rapidjsontest.make...
Generated gmake/jsonstat_sajsontest.make...
Generated gmake/jsonstat_sheredomjsonhtest.make...
Generated gmake/jsonstat_simplejsontest.make...
Generated gmake/jsonstat_strduptest.make...
Generated gmake/jsonstat_taocppjson.make...
Generated gmake/jsonstat_udpjsontest.make...
Generated gmake/jsonstat_ujson4ctest.make...
Generated gmake/jsonstat_vincenthzlibjsontest.make...
Generated gmake/jsonstat_voorheestest.make...
Generated gmake/jsonstat_yajltest.make...
Done (505ms).
sed: can't read s/,-x//: No such file or directory
```

**Comment by miloyip** [comment] 2016-01-23 06:41
I remembered that sed operation is needed in OSX (premake generated this unnecessary compilation flag). And I think the problem is that sed has different syntax between linux/OSX.

**Comment by xor-gate** [comment] 2016-01-23 09:58
The `build/machine.sh` doesn't work out of the box because it uses `/bin/sh` which is by default linked to the `/bin/dash` POSIX shell and it contains bash syntax:

```
Done (499ms).
+ ./machine.sh
./machine.sh: 2: ./machine.sh: [[: not found
#define MACHINE "AtomC2550@2.41GHz"
+ cd /nativejson-benchmark/bin
```

I have changed to `#!/usr/bin/env bash`, but for other unixes e.g: FreeBSD, NetBSD it wont work out of the box because bash is not installed and the default shell.

**Comment by xor-gate** [comment] 2016-01-23 10:02
I'm currently stuck with an compiler error, the procedure can be seen here: https://github.com/xor-gate/nativejson-benchmark/blob/dockerize/Dockerfile#L16-L17

```
Done (499ms).
#define MACHINE "AtomC2550@2.41GHz"
+ cd /nativejson-benchmark/build/gmake
+ make -f benchmark.make config=release64
make: Nothing to be done for 'all'.
+ make -f nativejson.make
Creating ../../bin


Creating ../../intermediate/release_x32/gmake/x32/release/nativejson
main.cpp
In file included from /usr/include/c++/4.9/algorithm:60:0,
                 from ../../src/main.cpp:1:
/usr/include/c++/4.9/utility:68:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
make: *** [../../intermediate/release_x32/gmake/x32/release/nativejson/main.o] Error 1
nativejson.make:164: recipe for target '../../intermediate/release_x32/gmake/x32/release/nativejson/main.o' failed
```

**Comment by xor-gate** [comment] 2016-01-23 10:12
It seems to compile now a little further, but having 32bit while instructing 64bit is a bit weird:

```
+ cd /nativejson-benchmark/build/gmake
+ make -f benchmark.make config=release64
make: Nothing to be done for 'all'.
+ make -f nativejson.make
Creating ../../bin
Creating ../../intermediate/release_x32/gmake/x32/release/nativejson
main.cpp
memorystat.cpp
arduinojsontest.cpp
cajuntest.cpp
```

It seems i'm still missing dependencies:
```
In file included from ../../thirdparty/cajun-jsonapi/include/cajun/json/elements.h:299:0,
                 from ../../thirdparty/cajun-jsonapi/include/cajun/json/reader.h:34,
                 from ../../src/tests/cajuntest.cpp:5:
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:92:36: warning: unused parameter 'array' [-Wunused-parameter]
    virtual void Visit(const Array& array) {}
                                    ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:93:37: warning: unused parameter 'object' [-Wunused-parameter]
    virtual void Visit(const Object& object) {}
                                     ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:94:37: warning: unused parameter 'number' [-Wunused-parameter]
    virtual void Visit(const Number& number) {}
                                     ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:95:37: warning: unused parameter 'string' [-Wunused-parameter]
    virtual void Visit(const String& string) {}
                                     ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:96:38: warning: unused parameter 'boolean' [-Wunused-parameter]
    virtual void Visit(const Boolean& boolean) {}
                                      ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:97:35: warning: unused parameter 'null' [-Wunused-parameter]
    virtual void Visit(const Null& null) {}
                                   ^
In file included from ../../thirdparty/cajun-jsonapi/include/cajun/json/elements.h:299:0,
                 from ../../thirdparty/cajun-jsonapi/include/cajun/json/reader.h:34,
                 from ../../src/tests/cajuntest.cpp:5:
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:112:30: warning: unused parameter 'array' [-Wunused-parameter]
    virtual void Visit(Array& array) {}
                              ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:113:31: warning: unused parameter 'object' [-Wunused-parameter]
    virtual void Visit(Object& object) {}
                               ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:114:31: warning: unused parameter 'number' [-Wunused-parameter]
    virtual void Visit(Number& number) {}
                               ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:115:31: warning: unused parameter 'string' [-Wunused-parameter]
    virtual void Visit(String& string) {}
                               ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:116:32: warning: unused parameter 'boolean' [-Wunused-parameter]
    virtual void Visit(Boolean& boolean) {}
                                ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:117:29: warning: unused parameter 'null' [-Wunused-parameter]
    virtual void Visit(Null& null) {}
                             ^
../../thirdparty/cajun-jsonapi/include/cajun/json/elements.inl:435:44: warning: unused parameter 'trivial' [-Wunused-parameter]
 inline bool Null::operator == (const Null& trivial) const
                                            ^
casablancatest.cpp
In file included from ../../src/tests/casablancatest.cpp:25:0:
../../thirdparty/casablanca/Release/src/pch/stdafx.h:77:34: fatal error: boost/thread/mutex.hpp: No such file or directory
 #include "boost/thread/mutex.hpp"
                                  ^
compilation terminated.
nativejson.make:176: recipe for target '../../intermediate/release_x32/gmake/x32/release/nativejson/casablancatest.o' failed
make: *** [../../intermediate/release_x32/gmake/x32/release/nativejson/casablancatest.o] Error 1
```

**Comment by xor-gate** [comment] 2016-01-23 10:21
Now i'm stuck because there is something wrong by using the C++ standard library for some odd reason.
I have no clue which compiler flags are passed to compile this piece of code.

```
configurutest.cpp
In file included from ../../src/tests/configurutest.cpp:6:0:
../../thirdparty/configuru/configuru.hpp:156:26: error: 'shared_ptr' in namespace 'std' does not name a template type
  using DocInfo_SP = std::shared_ptr<DocInfo>;
                          ^
../../thirdparty/configuru/configuru.hpp:159:3: error: 'DocInfo_SP' does not name a type
   DocInfo_SP doc;
   ^
../../thirdparty/configuru/configuru.hpp:163:22: error: expected ')' before 'd'
   Include(DocInfo_SP d, unsigned l) : doc(d), line(l) {}
                      ^
../../thirdparty/configuru/configuru.hpp:230:9: error: 'atomic' in namespace 'std' does not name a template type
    std::atomic<unsigned> _ref_count { 1 };
```

**Comment by miloyip** [comment] 2016-01-24 09:55
I just find out that configuru has missed some `#include`s. I am fixing them and will submit a PR.

**Comment by miloyip** [comment] 2016-01-24 10:09
I found that the upstream configuru has been [fixed](https://github.com/emilk/Configuru/blob/master/configuru.hpp) for this. I will update the library.

**Comment by miloyip** [comment] 2016-01-24 13:29
I completed the travis integration (#28), finally.

* udp/json-parser crashes in linux/gcc so I disabled it and reported this in https://github.com/udp/json-builder/issues/7 .
* configuru has missing headers but I have added them in the test directly. I made a PR https://github.com/emilk/Configuru/pull/1

**Comment by xor-gate** [comment] 2016-01-25 18:00
It now gets stuck at:

```shell
taocppjson.cpp
In file included from ../../thirdparty/taocppjson/include/tao/json/value.hh:15:0,
                 from ../../thirdparty/taocppjson/include/tao/json.hh:7,
                 from ../../src/tests/taocppjson.cpp:4:
../../thirdparty/taocppjson/include/tao/json/internal/asserts.hh:16:1: error: static assertion failed: internal consistency
 static_assert( sizeof( signed long ) == 8, "internal consistency" );
 ^
../../thirdparty/taocppjson/include/tao/json/internal/asserts.hh:17:1: error: static assertion failed: internal consistency
 static_assert( sizeof( unsigned long ) == 8, "internal consistency" );
 ^
In file included from ../../thirdparty/taocppjson/include/tao/json/internal/unescape_action.hh:8:0,
                 from ../../thirdparty/taocppjson/include/tao/json/internal/value_action.hh:11,
                 from ../../thirdparty/taocppjson/include/tao/json/internal/control.hh:12,
                 from ../../thirdparty/taocppjson/include/tao/json/from_string.hh:10,
                 from ../../thirdparty/taocppjson/include/tao/json.hh:12,
                 from ../../src/tests/taocppjson.cpp:4:
../../thirdparty/taocppjson/include/tao/json/internal/../external/pegtl/contrib/unescape.hh: In static member function 'static char tao_json_pegtl::unescape::unescape_c<T, Rs>::apply_two(char, const std::initializer_list<char>&, const std::initializer_list<char>&) [with T = tao::json::internal::rules::escaped_char; char ...Rs = {'\"', '\\', '/', '\010', '\014', '\012', '\015', '\011'}]':
../../thirdparty/taocppjson/include/tao/json/internal/../external/pegtl/contrib/unescape.hh:117:10: warning: control reaches end of non-void function [-Wreturn-type]
          }
          ^
In file included from ../../thirdparty/taocppjson/include/tao/json/internal/unescape_action.hh:8:0,
                 from ../../thirdparty/taocppjson/include/tao/json/internal/value_action.hh:11,
                 from ../../thirdparty/taocppjson/include/tao/json/internal/control.hh:12,
                 from ../../thirdparty/taocppjson/include/tao/json/from_string.hh:10,
                 from ../../thirdparty/taocppjson/include/tao/json.hh:12,
                 from ../../src/tests/taocppjson.cpp:4:
../../thirdparty/taocppjson/include/tao/json/internal/../external/pegtl/contrib/unescape.hh: In function 'I tao_json_pegtl::unescape::unhex_char(char) [with I = unsigned int]':
../../thirdparty/taocppjson/include/tao/json/internal/../external/pegtl/contrib/unescape.hh:67:7: warning: control reaches end of non-void function [-Wreturn-type]
       }
       ^
```

**Comment by miloyip** [comment] 2016-01-26 01:58
I have submitted an issue https://github.com/taocpp/json/issues/1
I found that I have not tested about 32-bit build on Travis CI. Will do it.

**Comment by miloyip** [comment] 2016-01-26 07:22
Workable Boost 32-bit distribution is not in whitelist of Travis. https://github.com/travis-ci/apt-package-whitelist/issues/2318
Need to wait until make it work on 32-bit build on Travis.

**Comment by xor-gate** [comment] 2016-01-26 07:36
But it is a little weird because I "force" release64 build and nativejson-benchmarks still tries to build release32? https://github.com/xor-gate/nativejson-benchmark/blob/dockerize/Dockerfile#L17

**Comment by miloyip** [comment] 2016-01-26 14:42
~~~
&& cd /nativejson-benchmark/build/gmake && make -f benchmark.make config=release64 && make -f nativejson.make \
~~~
The second one has not specified release64.
Besides, why not just running the Makfile at root?

**Comment by miloyip** [comment] 2016-01-26 14:44
And also, after upgrade to premake5, the config names have been changed to `release_x32` and `release_x64`.

**Comment by xor-gate** [comment] 2016-01-26 15:08
It now works and even runs benchmarks, until it says boom :-). I have no clue yet why it crashes. I have sufficient RAM (16GByte).

```
Benchmarking Performance of SimpleJSON (C++)
          Parse canada.json          ... 91.122 ms  23.559 MB/s
          Parse citm_catalog.json    ... Not support
          Parse twitter.json         ... Not support
      Stringify canada.json          ... 781.930 ms  2.745 MB/s
      Stringify citm_catalog.json    ... Segmentation fault (core dumped)
make: *** [all] Error 139
Makefile:11: recipe for target 'all' failed
```

**Comment by miloyip** [comment] 2016-01-26 15:39
Did the docker set limit on memory?

**Comment by xor-gate** [comment] 2016-01-26 16:50
As stated in the documentation it does not set any limits by default (https://docs.docker.com/engine/reference/run/#user-memory-constraints). And I did not specify a limit either. I did run the executable from the host OS (arch) in the debian container chrooted without docker and it seems also to crash.

```
Verifying SimpleJSON (C++) ...
Failed to parse 'citm_catalog.json'

Failed to parse 'twitter.json'
Failed
~~~~~ SNIP OUTPUT OF OTHER TESTS ~~~~~~
Benchmarking Performance of SimpleJSON (C++)
          Parse canada.json          ... 90.983 ms  23.595 MB/s
          Parse citm_catalog.json    ... Not support
          Parse twitter.json         ... Not support
      Stringify canada.json          ... 782.145 ms  2.745 MB/s
      Stringify citm_catalog.json    ... Segmentation fault (core dumped)
Makefile:11: recipe for target 'all' failed
```

```
root@shulgin:/nativejson-benchmark# gcc --version
gcc (Debian 4.9.2-10) 4.9.2
```

Your executable has also some stuff hardcoded because when I run `./bin/nativejson_release_x64_gmake` it crashes but when I do `cd bin; ./nativejson_release_x64_gmake`  then it runs.

**Comment by miloyip** [comment] 2016-01-26 17:07
The working path is necessary for loading sample data files.
If a library causes crash, I will try to disable it in xxxtest.cpp. If possible, can try to reproduce in an independent program and debug it.
But anyway, this seems getting good progress.

**Comment by miloyip** [comment] 2016-01-26 17:08
Besides, I still suggest running Makefile at root. So future any updates will not need to change in different places.

**Comment by xor-gate** [comment] 2016-01-26 17:09
Maybe good would be to test yourself native in a debian 8 jessie amd64 environment (VM or so), that would make debugging easier for the `SimpleJSON (C++)` segfault.

**Comment by xor-gate** [comment] 2016-01-26 17:10
I run in the Dockerfile from sourcecode root path the makefile. Should I create a pull request because the segfault should be handled in a other issue?

**Comment by miloyip** [comment] 2016-01-26 17:13
Yes. Please go ahead.

**Comment by xor-gate** [comment] 2016-01-26 17:20
I will leave this issue open until it works completely so we can discuss further, the docker build was not finished because of the previous segfault. So this means my command to generate html could still fail. This draft could be merged and other people can test it also. Maybe the README could be updated with a Docker section to let people know how to build it ?

**Closed** 2016-01-26 17:48 UTC
